name: Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test_bundled:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
    - name: Test bundled
      run: |
        wasm-pack test --chrome --headless --features relaxed-idb
    - name: Test custom-libc
      if: matrix.os != 'windows-latest'
      run: |
        cd examples/custom-libc
        RUSTFLAGS="-L $(pwd)" wasm-pack test --chrome --headless

  test_bundled_sqlite3mc:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
    - name: Test bundled sqlite3mc
      run: |
        wasm-pack test --chrome --headless --features relaxed-idb,sqlite3mc

  test_bundled_sqlite_vec:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
    - name: Test bundled sqlite-vec
      run: |
        wasm-pack test --chrome --headless --features relaxed-idb,sqlite-vec

  test_diesel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
    - name: Run diesel tests
      run: |
        git clone https://github.com/diesel-rs/diesel.git
        cd diesel
        rustup target add wasm32-unknown-unknown
        cargo install wasm-bindgen-cli
        printf "[patch.crates-io]\n" >> Cargo.toml
        printf "sqlite-wasm-rs = { path = \"..\" }\n" >> Cargo.toml
        WASM_BINDGEN_TEST_TIMEOUT=120 cargo xtask run-tests --wasm sqlite

  test_rusqlite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
    - name: Run rusqlite tests
      run: |
        git clone https://github.com/Spxg/rusqlite.git
        cd rusqlite
        printf "[patch.crates-io]\n" >> Cargo.toml
        printf "sqlite-wasm-rs = { path = \"..\" }\n" >> Cargo.toml
        WASM_BINDGEN_TEST_TIMEOUT=60 wasm-pack test --chrome --headless --features modern-base

  test_clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check clippy
      run: |
        cargo clippy --no-default-features --features precompiled,relaxed-idb -- -D warnings

  test_implement_a_vfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
    - name: Test implement-a-vfs example
      run: |
        cd examples/implement-a-vfs
        wasm-pack test --chrome --headless -- -- --nocapture

  test_fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test rustfmt
      run: cargo fmt --check

  test_precompiled:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Test
      run: |
        wasm-pack test --chrome --headless --no-default-features --features precompiled,relaxed-idb

  test_atomics:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
    - name: Test
      run: |
        rustup toolchain install nightly
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
        RUSTFLAGS='-Ctarget-feature=+atomics -Clink-args=--shared-memory -Clink-args=--max-memory=1073741824 -Clink-args=--import-memory -Clink-args=--export=__wasm_init_tls -Clink-args=--export=__tls_size -Clink-args=--export=__tls_align -Clink-args=--export=__tls_base' rustup run nightly wasm-pack test --chrome --headless --features relaxed-idb -Z build-std=panic_abort,std

  test_msrv:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
      with:
        version: '3.1.52'
    - name: Test MSRV
      run: |
        rustup toolchain install 1.78.0
        rustup default 1.78.0
        wasm-pack test --chrome --headless --features relaxed-idb
        wasm-pack test --chrome --headless --features relaxed-idb,sqlite3mc
        wasm-pack test --chrome --headless --features relaxed-idb,sqlite-vec

  test_nodejs:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
    - name: Test
      run: |
        cd examples/nodejs
        wasm-pack build --target nodejs
        node pkg/nodejs.js
